try again

diff --git a/.github/workflows/ci_cd_wf.yml b/.github/workflows/ci_cd_wf.yml
--- a/.github/workflows/ci_cd_wf.yml
+++ b/.github/workflows/ci_cd_wf.yml
@@ -1,4 +1,4 @@
-name: tests
+name: test
 
 permissions: write-all
 
@@ -27,12 +27,23 @@ jobs:
         run: |
           python -m pip install -r requirements.txt
           
+      - name: Run tests
+        run: |
+          python -m pytest -v tests
+
       - name: Build coverage file
         run: |
-          pytest --junitxml=pytest.xml --cov-report term-missing:skip-covered --cov=. | tee pytest-coverage.txt
+          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov . | tee pytest-coverage.txt
 
       - name: Pytest coverage comment
         uses: MishaKav/pytest-coverage-comment@main
         with:
           pytest-coverage-path: ./pytest-coverage.txt
           junitxml-path: ./pytest.xml
+
+      - name: Check test results and mark workflow as failed if necessary
+        run: |
+          if grep -q 'FAILED' pytest-coverage.txt; then
+            echo 'Test case failed. Marking workflow as failed.'
+            exit 1
+          fi
